config/routes.rb
Rails.application.routes.draw do
  resources :projects

  root to: 'projects#index'
end

app/models/entities/project.rb
module Entities
  class Project < Entity
    def self.model_name
      ActiveModel::Name.new(self, nil, 'Project')
    end
  end
end

app/models/entity.rb
class Entity < ROM::Struct
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  def self.inherited(klass)
    super

    klass.transform_types { |t| t.omittable }
  end

  def persisted?
    try(:id).present?
  end
end

app/controllers/application_controller.rb
require 'dry/monads/result'

class ApplicationController < ActionController::Base
  include Dry::Monads[:result]
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    render :index, locals: { projects: projects.all }
  end

  def show
    render :show, locals: { project: projects.find(params[:id]) }
  end

  def new
    render :new, locals: { project: projects.build }
  end

  def create
    case projects.create(project_params)
    in Success(Entities::Project => project)
      redirect_to projects_path, notice: 'Project has been created'
    in Failure(errors: Dry::Validation::MessageSet => errors, project: Entities::Project => project)
      flash.now[:alert] = 'Project could not be created'
      render :new, locals: { errors: errors, project: project }
    end
  end

  private

  def projects
    @projects ||= ProjectsContext.new
  end

  def project_params
    params.require(:project).permit(:name).to_h.symbolize_keys
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors
    assigns['error']
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExplodingRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h2>Projects</h2>

<%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>

<ul>
  <% projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render 'shared/error_messages', errors: errors %>

<%= form_with model: project, scope: :project do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit 'Create Project', class: 'btn btn-primary' %>
<% end %>

app/views/projects/projects/new.html.erb
<h2>New Project</h2>

<%= form_with model: @project, scope: :project do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit 'Create Project', class: 'btn btn-primary' %>
<% end %>

app/views/projects/show.html.erb
<h2><%= project.name %></h2>

app/views/shared/_error_messages.html.erb
<p>There were errors that prevented this form from being saved:</p>

<% if errors.present? %>
  <% errors.map do |error| %>
    <li><%= error.path.first.to_s.capitalize %> <%= error.text %></li>
  <% end %>
<% end %>